### ISSUE TITLE
Consider picking a license

### ISSUE THREAD

**Issue by pavloconuve** [conceptualitis/mahogany#3]
While I understand that this is a joke project, it still can be beneficial to some. Just putting the code on Github public repo doesn't give any rights to use, copy or extend it. Please consider picking an open-source license, like [MIT License](https://opensource.org/licenses/MIT).

For more information, see Codding Horror awesome post [Pick a License, Any License](https://blog.codinghorror.com/pick-a-license-any-license/).

**Comment by conceptualitis** [comment]
No worries - I'll add a `LICENSE` file reflective of what's in the `package.json` this weekend.

**Comment by conceptualitis** [comment]
![license added](https://media.giphy.com/media/SRGpALDA3i5va/giphy.gif)
